name: Build and Deploy
on:
  - push
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create Blog from Markdown Files
        uses: kamranahmedse/github-pages-blog-action@v0.0.10

